---
- name: Monitor CPU Usage and Trigger Email Alert
  hosts: all
  become: yes
  vars_files:
    - secret.yml

  tasks:
    - name: Get CPU usage statistics
      shell: |
        top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\([0-9.]*\)%* id.*/\1/' | awk '{print 100 - $1}'
      register: cpu_usage
      changed_when: false

    - name: Get top 5 CPU consuming processes
      shell: |
        ps -eo user,pid,ppid,cmd,%cpu --sort=-%cpu | head -n 6
      register: top_cpu_processes
      changed_when: false

    - name: Format top 5 CPU consuming processes
      shell: |
        echo '{{ top_cpu_processes.stdout }}' | awk '{printf "%-10s %-8s %-8s %-50s %-8s\n", $1, $2, $3, $4, $5}'
      register: formatted_top_cpu_processes
      changed_when: false

    - name: Generate timestamp
      shell: |
        date +"%Y-%m-%d %H:%M:%S"
      register: current_time

    - name: Generate email alert content if CPU usage is above 80%
      shell: |
        echo -e "Dear Team,\n\nThis is an automated alert from the Ansible CPU Utilization Monitoring System. The CPU usage has been above 80% on {{ inventory_hostname }} over the last hour. \n\nCurrent CPU Usage Data:\n\n{{ cpu_usage.stdout }}%\n\nTop 5 CPU Consuming Processes:\n\n{{ formatted_top_cpu_processes.stdout }}\n\nKindly take the necessary actions to address this issue at the earliest.\n\nRegards,\nAnsible Automation" > /tmp/cpu_usage_email_{{ inventory_hostname }}.txt
      when: cpu_usage.stdout | float < 80
      delegate_to: localhost

- name: Send Email Alerts
  hosts: localhost
  become: yes
  vars_files:
    - secret.yml
  tasks:

    - name: Send email alert if CPU utilization exceeds 80% using mailx
      shell: |
        for file in /tmp/cpu_usage_email_*.txt; do
          if [ -s $file ]; then
            cat $file | /usr/bin/mailx -s "Alert! High CPU Utilization on $(basename $file .txt | cut -d'_' -f4): at  $(date)" -S smtp="smtp.gmail.com:587" -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user="{{ smtp_user }}" -S smtp-auth-password="{{ smtp_password }}" -S ssl-verify=ignore rampeesakiran3@gmail.com;
          fi
        done

    - name: Remove previous run data
      shell: |
        for file in /tmp/cpu_usage_email_*.txt; do rm -rf $file;done

